CREATE DATABASE [covid19_db]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [covid19_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [covid19_db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [covid19_db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [covid19_db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [covid19_db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [covid19_db] SET ARITHABORT OFF 
GO

ALTER DATABASE [covid19_db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [covid19_db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [covid19_db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [covid19_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [covid19_db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [covid19_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [covid19_db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [covid19_db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [covid19_db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [covid19_db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [covid19_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [covid19_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [covid19_db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [covid19_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [covid19_db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [covid19_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [covid19_db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [covid19_db] SET RECOVERY FULL 
GO

ALTER DATABASE [covid19_db] SET  MULTI_USER 
GO

ALTER DATABASE [covid19_db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [covid19_db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [covid19_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [covid19_db] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [covid19_db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [covid19_db] SET  READ_WRITE 
GO


